[versions]
# Core
agp = "8.9.2"
fragmentKtx = "1.8.9"
glide = "5.0.5"
kotlin = "2.2.0"
activityKtx = "1.11.0"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
kotlin-serialization-plugin = "2.0.0"
kotlin-serialization-json = "1.6.3"

# Testing
junit = "4.13.2"
junitExt = "1.3.0"
espresso = "3.7.0"

# Lifecycle
lifecycle = "2.9.4"

# Network
retrofit = "3.0.0"
okhttp = "5.1.0"

# Dagger/Hilt
hilt = "2.54"

# DataStore
datastore = "1.1.7"

# Google Service & Firebase
google-services = "4.4.4"
firebaseBom = "34.4.0"
credentials = "1.5.0"
googleid = "1.1.1"
playServicesAuth = "21.4.0"


# Coruitines support
kotlinxCoroutinesPlayServices = "1.9.0"
viewpager2 = "1.1.0"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization-plugin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services" , version.ref = "google-services"}

[libraries]
# Core
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization-json" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

# Lifecycle
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }

# Network
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# Dagger/Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

# DataStore
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# Google Service & Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }


# Coroutines support
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesPlayServices" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }


[bundles]
core = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "material",
    "kotlin-serialization-json",
    "androidx-activity-ktx",
    "androidx-activity",
    "androidx-constraintlayout",
    "androidx-fragment-ktx",
]

testing = [
    "junit",
    "androidx-junit",
    "androidx-espresso-core"
]

lifecycle = [
    "lifecycle-runtime",
    "lifecycle-viewmodel",
    "lifecycle-livedata-ktx",
]

network = [
    "retrofit",
    "converter-gson",
    "okhttp",
    "logging-interceptor"
]

hilt = [
    "hilt-android",
]

google-firebase = [
    "firebase-auth",
    "androidx-credentials",
    "androidx-credentials-play-services-auth",
    "googleid",
    "play-services-auth",
]

coroutine = [
    "kotlinx-coroutines-android",
    "kotlinx-coroutines-play-services",
]



#implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7")